### ISSUE TITLE
Why is it called sysechk?

### ISSUE THREAD

**Issue by BarbzYHOOL** [infertux/sysechk#2]
Why not syscheck? :'(

**Comment by infertux** [comment]
Haha, it's just a bad contraction of the full name: System Security Checker --> SysSecChk --> SySeChk. I must admit this was a pretty poor idea. The project is kinda dead anyway...

**Comment by BarbzYHOOL** [comment]
bash scripts never die :P

**Comment by infertux** [comment]
@BarbzYHOOL If you find the project useful and want to take over development and/or maintenance of it, I'd be happy to give you commit access. Just saying :)

**Comment by BarbzYHOOL** [comment]
I wouldn't know what to do and only tried the script once (but plan to retry it soon). So I guess that's not gonna happen :D

But I found some very old bash scripts that I still use today, so I think this will still be useful to me !
